### ISSUE TITLE
Laravel Horizon freezes Laravel on latest Docker update.

### ISSUE THREAD

**Issue by mattoz0** [laravel/horizon#1085]
- Horizon Version: v5.7.13
- Laravel Version: v8.61.0
- PHP Version: v8.0.11
- Redis Driver & Version: ~~predis~~/phpredis 5.3.4
- Database Driver & Version: mysqlnd 8.0.11
- Docker version: Docker version 20.10.8, build 3967b7d (Mac)
- Docker compose version: docker-compose version 1.29.2, build 5becea4c

### Description:
After updating to the latest Docker Desktop, Laravel Horizon will freeze Laravel when run. 

### Steps To Reproduce:

Here is a minimum docker-compose.yml
```
version: "3.9"

volumes:
  dbdata:
    driver: local
  elasticdata:
    driver: local
  redisdata:
    driver: local

services:
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: taggedlaravel:latest
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    dns:
      - 172.52.0.101
    networks:
      - app-network
    depends_on:
      - dns

  queue:
    image: taggedlaravel:latest
    container_name: queue
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    entrypoint: "php artisan horizon"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - redis
      - app

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw,delegated
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql/:rw,delegated
    networks:
      - app-network
    depends_on:
      - dns

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data:rw,delegated
    networks:
      - app-network
    depends_on:
      - dns

#Docker Networks
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.52.0.0/16
```

1. run docker-compose up
2. run docker exec -it app php artisan horizon
3. try to load webpage

Expected result: Page loads and queue work is being done.
Actual result: Laravel freezes, page doesn't load, queue work isn't being done.

I also tried creating a Horizon only container with an entry point 
``` 
queue:
    image: laravel
    container_name: queue
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    entrypoint: "php artisan horizon"
    volumes:
     - ./:/var/www
    networks:
      - app-network
    depends_on:
      - redis
      - app
```

This also resulted in the same problem with the following steps:
1. docker-compose up
2. try load webpage

Expected result: Page loads and queue work is being done.
Actual result: Laravel freezes, page doesn't load, queue work isn't being done.

If you then:
1. docker-compose stop queue
2. try load webpage

the page will now load as per normal while horizon isn't running.

# Tried the following steps to resolve.
- Changed volume mounts to NFS (check if I/O speed was the issue).
- Tried moving horizon to its own container (in case process was hogging cpu thread).
