### ISSUE TITLE
Display entire table on large screens

### ISSUE THREAD

**Issue by freekmurze** [laravel/horizon#181]
It would be nice if Horizon would make better use of available screen real estate.

![screen shot 2017-10-04 at 17 50 36](https://user-images.githubusercontent.com/483853/31185692-eb30a5c0-a92c-11e7-90f3-0b7b44589ae0.png)

**Comment by pavinthan** [comment]
You can customize it.

**Comment by browner12** [comment]
How about this for a PR  to `resources/assets/less/_objects.wraps.less`?

```less
.wrapper {
  width: 940px;
  margin-left: auto;
  margin-right: auto;
}
```

changed to -->

```less
.wrapper {
  width: 95%;
  min-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
```
